FROM gradle:jdk25-alpine@sha256:9c6d10f0380c29b629fc4d61950da365b6ab33a70adb64b8d7ef496962df0bf5 AS build
LABEL authors="Mallne"

RUN addgroup -g 1001 -S buildgroup && adduser -u 1001 -G buildgroup -S builduser

WORKDIR /app
COPY . .

RUN --mount=type=secret,id=nexus_username \
    --mount=type=secret,id=nexus_password \
    NEXUS_USERNAME=$(cat /run/secrets/nexus_username) \
    NEXUS_PASSWORD=$(cat /run/secrets/nexus_password) \
    gradle clean shadowJar --stacktrace "-Dorg.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m" --no-daemon

FROM eclipse-temurin:25-alpine@sha256:3fd2d245c4e0eba615fe366a71b8bd25f5db7104f53e4026b24bf508b880bd2a AS app
RUN apk add --no-cache curl

ARG UID=1000
ARG GID=1000
RUN addgroup -g $GID appuser && adduser -u $UID -G appuser -D -S appuser
USER appuser

WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/app.jar

ENV BEHIND_PROXY=${BEHIND_PROXY:-FALSE}
ENV ENABLE_CORS=${ENABLE_CORS:-FALSE}
ENV SECURITY_ENABLED=${SECURITY_ENABLED:-TRUE}
ENV SECURITY_ISSUER=${SECURITY_ISSUER}
ENV SECURITY_SCOPES=${SECURITY_SCOPES}
ENV SECURITY_CLIENTID=${SECURITY_CLIENTID}
ENV SECURITY_CLIENTSECRET=${SECURITY_CLIENTSECRET}
ENV SECURITY_ROLESCOPE=${SECURITY_ROLESCOPE}
ENV SECURITY_GROUPS_USER=${SECURITY_GROUPS_USER}
ENV SECURITY_GROUPS_ADMIN=${SECURITY_GROUPS_ADMIN}
ENV SECURITY_GROUPS_SUPERADMIN=${SECURITY_GROUPS_SUPERADMIN}
ENV DATA_URL=${DATA_URL}
ENV DATA_USER=${DATA_USER}
ENV DATA_PASSWORD=${DATA_PASSWORD}
ENV TLSENABLED=${TLSENABLED:-TRUE}
ENV HOSTNAME=${HOSTNAME:-api.areaassist.mallne.cloud}
ENV CATALYST_TLSENABLED=${CATALYST_TLSENABLED:-TRUE}
ENV CATALYST_SERVERNAME=${CATALYST_SERVERNAME:-api.areaassist.mallne.cloud}
ENV SECURITY_AREAASSIST_CLIENTID=${SECURITY_AREAASSIST_CLIENTID}
ENV SECURITY_AREAASSIST_CLIENTNAME=${SECURITY_AREAASSIST_CLIENTNAME}
ENV SECURITY_AREAASSIST_ACCOUNTCONSOLE=${SECURITY_AREAASSIST_ACCOUNTCONSOLE}
ENV DATA_AUTOCREATEDELTA=${DATA_AUTOCREATEDELTA:-FALSE}
ENV DATA_MIGRATIONNAME=${DATA_MIGRATIONNAME:-V0__create.generated}

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:8080/health | grep RUNNING || exit 1
STOPSIGNAL SIGTERM
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
