### GET request to example server
GET {{server}}
#Authorization: Bearer {{$auth.token("keycloak")}}

### GET all Services
GET {{server}}/services
Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json

### GET all Baked in Services
GET {{server}}/services/builtin
Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json

### Ingest all Baked in Services
GET {{server}}/services/builtin/ingest
Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json