### GET request to example server
GET {{server}}
#Authorization: Bearer {{$auth.token("keycloak")}}

### GET all Services
GET {{server}}/services
Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json

### GET all Baked in Services
GET {{server}}/services/builtin
Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json

###
GET https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs?SERVICE=WFS&REQUEST=GetCapabilities&
    VERSION=2.0.0